#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vanlthpc07042_Csharp2_ASM_GD2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QUANLYXEHONDA")]
	public partial class qlxHDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLOAIXE(LOAIXE instance);
    partial void UpdateLOAIXE(LOAIXE instance);
    partial void DeleteLOAIXE(LOAIXE instance);
    partial void InsertTHONGTINXE(THONGTINXE instance);
    partial void UpdateTHONGTINXE(THONGTINXE instance);
    partial void DeleteTHONGTINXE(THONGTINXE instance);
    #endregion
		
		public qlxHDDataContext() : 
				base(global::Vanlthpc07042_Csharp2_ASM_GD2.Properties.Settings.Default.QUANLYXEHONDAConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public qlxHDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlxHDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlxHDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public qlxHDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LOAIXE> LOAIXEs
		{
			get
			{
				return this.GetTable<LOAIXE>();
			}
		}
		
		public System.Data.Linq.Table<THONGTINXE> THONGTINXEs
		{
			get
			{
				return this.GetTable<THONGTINXE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIXE")]
	public partial class LOAIXE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoaiXe;
		
		private string _TenLoaiXe;
		
		private EntitySet<THONGTINXE> _THONGTINXEs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiXeChanging(string value);
    partial void OnMaLoaiXeChanged();
    partial void OnTenLoaiXeChanging(string value);
    partial void OnTenLoaiXeChanged();
    #endregion
		
		public LOAIXE()
		{
			this._THONGTINXEs = new EntitySet<THONGTINXE>(new Action<THONGTINXE>(this.attach_THONGTINXEs), new Action<THONGTINXE>(this.detach_THONGTINXEs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiXe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoaiXe
		{
			get
			{
				return this._MaLoaiXe;
			}
			set
			{
				if ((this._MaLoaiXe != value))
				{
					this.OnMaLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiXe = value;
					this.SendPropertyChanged("MaLoaiXe");
					this.OnMaLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoaiXe", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenLoaiXe
		{
			get
			{
				return this._TenLoaiXe;
			}
			set
			{
				if ((this._TenLoaiXe != value))
				{
					this.OnTenLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._TenLoaiXe = value;
					this.SendPropertyChanged("TenLoaiXe");
					this.OnTenLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIXE_THONGTINXE", Storage="_THONGTINXEs", ThisKey="MaLoaiXe", OtherKey="MaLoaiXe")]
		public EntitySet<THONGTINXE> THONGTINXEs
		{
			get
			{
				return this._THONGTINXEs;
			}
			set
			{
				this._THONGTINXEs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THONGTINXEs(THONGTINXE entity)
		{
			this.SendPropertyChanging();
			entity.LOAIXE = this;
		}
		
		private void detach_THONGTINXEs(THONGTINXE entity)
		{
			this.SendPropertyChanging();
			entity.LOAIXE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGTINXE")]
	public partial class THONGTINXE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaXe;
		
		private string _MaLoaiXe;
		
		private string _TenXe;
		
		private double _Gia;
		
		private string _MauXe;
		
		private int _DongCo;
		
		private double _KhoiLuong;
		
		private EntityRef<LOAIXE> _LOAIXE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaXeChanging(string value);
    partial void OnMaXeChanged();
    partial void OnMaLoaiXeChanging(string value);
    partial void OnMaLoaiXeChanged();
    partial void OnTenXeChanging(string value);
    partial void OnTenXeChanged();
    partial void OnGiaChanging(double value);
    partial void OnGiaChanged();
    partial void OnMauXeChanging(string value);
    partial void OnMauXeChanged();
    partial void OnDongCoChanging(int value);
    partial void OnDongCoChanged();
    partial void OnKhoiLuongChanging(double value);
    partial void OnKhoiLuongChanged();
    #endregion
		
		public THONGTINXE()
		{
			this._LOAIXE = default(EntityRef<LOAIXE>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaXe", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaXe
		{
			get
			{
				return this._MaXe;
			}
			set
			{
				if ((this._MaXe != value))
				{
					this.OnMaXeChanging(value);
					this.SendPropertyChanging();
					this._MaXe = value;
					this.SendPropertyChanged("MaXe");
					this.OnMaXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoaiXe", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string MaLoaiXe
		{
			get
			{
				return this._MaLoaiXe;
			}
			set
			{
				if ((this._MaLoaiXe != value))
				{
					if (this._LOAIXE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiXeChanging(value);
					this.SendPropertyChanging();
					this._MaLoaiXe = value;
					this.SendPropertyChanged("MaLoaiXe");
					this.OnMaLoaiXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenXe", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TenXe
		{
			get
			{
				return this._TenXe;
			}
			set
			{
				if ((this._TenXe != value))
				{
					this.OnTenXeChanging(value);
					this.SendPropertyChanging();
					this._TenXe = value;
					this.SendPropertyChanged("TenXe");
					this.OnTenXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float NOT NULL")]
		public double Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MauXe", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MauXe
		{
			get
			{
				return this._MauXe;
			}
			set
			{
				if ((this._MauXe != value))
				{
					this.OnMauXeChanging(value);
					this.SendPropertyChanging();
					this._MauXe = value;
					this.SendPropertyChanged("MauXe");
					this.OnMauXeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DongCo", DbType="Int NOT NULL")]
		public int DongCo
		{
			get
			{
				return this._DongCo;
			}
			set
			{
				if ((this._DongCo != value))
				{
					this.OnDongCoChanging(value);
					this.SendPropertyChanging();
					this._DongCo = value;
					this.SendPropertyChanged("DongCo");
					this.OnDongCoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KhoiLuong", DbType="Float NOT NULL")]
		public double KhoiLuong
		{
			get
			{
				return this._KhoiLuong;
			}
			set
			{
				if ((this._KhoiLuong != value))
				{
					this.OnKhoiLuongChanging(value);
					this.SendPropertyChanging();
					this._KhoiLuong = value;
					this.SendPropertyChanged("KhoiLuong");
					this.OnKhoiLuongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIXE_THONGTINXE", Storage="_LOAIXE", ThisKey="MaLoaiXe", OtherKey="MaLoaiXe", IsForeignKey=true)]
		public LOAIXE LOAIXE
		{
			get
			{
				return this._LOAIXE.Entity;
			}
			set
			{
				LOAIXE previousValue = this._LOAIXE.Entity;
				if (((previousValue != value) 
							|| (this._LOAIXE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIXE.Entity = null;
						previousValue.THONGTINXEs.Remove(this);
					}
					this._LOAIXE.Entity = value;
					if ((value != null))
					{
						value.THONGTINXEs.Add(this);
						this._MaLoaiXe = value.MaLoaiXe;
					}
					else
					{
						this._MaLoaiXe = default(string);
					}
					this.SendPropertyChanged("LOAIXE");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
